# Generated by Django 4.2.7 on 2023-12-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.URLField()),
                ('short', models.CharField(max_length=70)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
