# Generated by Django 4.2.7 on 2023-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
